### ISSUE TITLE
Inconsistent results from each run on large inputs

### ISSUE THREAD

**Issue by hwang018** [jerednel/markov-chain-attribution#1]
Hi Nelson,

Thanks for crafting out python version of ChannelAttribution! 
While trying out your script on my input dataframe (~0.5M rows, niter = 5000), I found that the script seems to generate inconsistent results each time it runs on the same input. In my 0.5 Million rows input, there are ~2000 rows ending with conv and the rest ends with null. Not only the results are different at each run, some channels will have 0 markov conversions assigned at some run.

However, when I used only the 2000 converted rows as the input to the script, the script is able to generate consistent results across different runs. (niter = 5000)

May I seek your opinion on what could have induced this result? Would you have any suggestion on how to set up the niter? I have tried using niter = 50000 and still observe some inconsistency between runs.

Thank you!
Wang

**Comment by jerednel** [comment]
Hello - thanks for testing this out!  It's important to note that this library does not solve the problem analytically, but rather, probabilistically through simulations.  This means that there will be differences in the sum of Markov conversions on each run however they should converge to a similar count the more simulations that are run.  

What _would_ be bad, though, is if the conversion counts that are being allocated to a given channel are significantly different on each run.  Are you seeing the results vary to the point of not making sense each time you run this? (e.g. when allocating your 2k conversions, on trial 1 there are 400 allocated to channel A and on trial 2 there are 0) Or are the variations within an acceptable realm?

If you could provide the degree of variation between the same channel for your trials that'd help me trace this down.

**Comment by hwang018** [comment]
Hi Nelson, here are 2 results from the same input dataframe and indeed some channel, in this case channel_1 become -0.0 in one run. Similar case happens and the variation also fluctuates..
The particular thing is that consistent results can be simulated under small input (tried 2000 rows at niter = 5000), but when I tried the full dataframe with 0.5M rows, these fluctuating results would happen and sometimes 2 channels' markov conversions will be 0..

{'channel_1': -0.0,
 'channel_2': 182.26428571428576,
 'channel_3': 38.37142857142866,
 'channel_4': 402.90000000000003,
 'channel_5': 508.42142857142846,
 'channel_6': 211.04285714285706}

{'channel_1': 61.045454545454525,
 'channel_2': 183.1363636363637,
 'channel_3': 54.26262626262624,
 'channel_4': 413.75252525252523,
 'channel_5': 325.57575757575745,
 'channel_6': 305.22727272727275}

**Comment by jerednel** [comment]
Ok thank you for highlighting this.  I will try to recreate and see if I can get a fix for this sometime soon.

**Comment by jerednel** [comment]
Ok Wang - I updated this quite a bit.  It no longer runs based on simulations and instead solves analytically (so no need to pass the `niter` argument).  This should make it run much quicker and provide you consistent (reliable) results every time. Run `pip install markov-model-attribution==0.3` and try running your data through it.

**Comment by jerednel** [comment]
Closing this for now since this has been resolved.
