### ISSUE TITLE
Negative Conversions

### ISSUE THREAD

**Issue by harisbitsakou** [jerednel/markov-chain-attribution#2]
Hello Jeremy!!

Thank you very much for this library and article!!
I am using the latest (0.3) version of your library, but I still get negative conversions (an issue which is as resolved in this version). I was wandering if you could please, give some guidance on how to tackle this issue??

Thank you very much once again!!!
Haris

**Comment by jerednel** [comment]
Hi Haris, can you run `pip install markov-model-attribution==0.31` and rerun your data and let me know what the output is of the model for the new objects returned for "transition_matrix", and "absorption_matrix"?

**Comment by harisbitsakou** [comment]
Hello Jeremy!
Thank you very much for your prompt response! 
Please, find attached two excel files with the results returned for the transition and absorption matrix.

Looking forward to hearing from you :)
[absorption_matrix.xlsx](https://github.com/jerednel/markov-chain-attribution/files/3285305/absorption_matrix.xlsx)
[transition_matrix.xlsx](https://github.com/jerednel/markov-chain-attribution/files/3285306/transition_matrix.xlsx)

**Comment by jerednel** [comment]
I can see that, for example, c121 has a 5.88% chance of moving to null and no other probability of moving anywhere else.  This shouldn't be possible.  Can you confirm you have 375 unique states (including start and conv)in your original dataset?  I want to make sure some columns did not get truncated somewhere along the way.

**Comment by harisbitsakou** [comment]
Hello Jeremy!

Thank you very much for your reply. Yes, in my original dataset I have 375 channels in total (372 + 3 (start, null and conv) )

Looking forward to hearing from you :)

**Comment by gosdra** [comment]
I second the above problem. Also for the transition probabilities from one state to every combination possible does not sum to 1 for some of the channels.

**Comment by jerednel** [comment]
> I second the above problem. Also for the transition probabilities from one state to every combination possible does not sum to 1 for some of the channels.

Are you able to share a dataset to help me reproduce?  You can either attach here or email it to me jeremy@nelson.eu.org

**Comment by gosdra** [comment]
Sent you an email. Thanks!

**Comment by jerednel** [comment]
Thanks @gosdra - This was an issue with generating the unique_touch_list and has been resolved.
