### ISSUE TITLE
Error when evaluating whether channel is contained in path

### ISSUE THREAD

**Issue by gosdra** [jerednel/markov-chain-attribution#3]
Hi again! I found a bug in your code, which would probably go unobserved in most cases. This is the statement in question which is found when calculating transition states and transition probabilities:

`indices = [i for i, s in enumerate(user_path) if possible_state in s] `
`index = [i for i, s in enumerate(transitionStates) if state + '>' in s]`

So for here when we evaluate if a channel (possible_state) is in the list (s) the loop will evaluate the statement based on whether in contains that string combination, instead of matching the exact string.
For example: 'facebook' in 'facebook/refferal' will evaluate to True. 
You should replace 'in' with '==' to avoid errors in your calcs in both functions.

**Comment by jerednel** [comment]
Thanks for bringing this up! I think it makes sense to update the first list comprehension statement but the second one should be covered by the introduction of '>' no?

i.e. "Facebook>" will be different from "Facebook/referral>" so will not trigger incorrectly

Let me know if I'm missing anything.

**Comment by jerednel** [comment]
I suppose "facebook>" in "prefixfacebook>" would trigger this as well actually.

**Comment by jerednel** [comment]
I pushed an update to account for the scenarios you've highlighted.    Thanks!
