### ISSUE TITLE
Can we generate attributions and Removal effects without 'Start' state

### ISSUE THREAD

**Issue by naadvar** [jerednel/markov-chain-attribution#4]
Hello ,

I am currently trying to model a Marketing Multi-Channel Attribution. All the articles and the packages I have come across use a special "start" state and the removal effect is calculated based on that start state 

My question primarily is of two parts:

1. - Can we consider the first touch as the start state of each path.
2. - How can we calculate the removal effect if there is no "start "state( any documentation or an explanation of the formula would be really helpful)

**Comment by jerednel** [comment]
Practically, I'm not sure how the system would exist if there was no state prior to exposure to a touchpoint.  Conceptually I can understand a circular system in which there is no initial state but I think you'll end up with weird side effects especially when it comes to low-frequency touchpoints that are high converting.  

As an example, I think that an 80% converting tactic that has a 1% chance of being somebody's first touch would be given much more weight than it it probably should if we ignored start state.

**Comment by naadvar** [comment]
Hey, thank you for your reply. This makes a lot of sense.
