### ISSUE TITLE
Dead Link for markov chain attribution modeling in readme.md

### ISSUE THREAD

**Issue by vaidyaprasad84** [jerednel/markov-chain-attribution#7]
The link in README.md pointing to markov chain attribution modeling (https://www.avayant.com/post/building-an-attribution-model-with-markov-chains) is a dead link. Its not working. 

Thanks,
![Deadlink](https://github.com/user-attachments/assets/c5a34b72-65c8-43d7-aa17-a0d52be6193c)

**Comment by jerednel** [comment]
Thank you for this.Added
